--- 
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: python-app-pdb
spec:
  minAvailable: {{ .Values.pdbMinAvailable }}
  selector:
    matchLabels:
      app: python-app-deployment 
