apiVersion: v1
kind: ServiceAccount
metadata:
  name: "python-app-service-account-{{ .Release.Namespace }}"
  labels:
    account: "python-app-service-account-{{ .Release.Namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "python-app-service-role-{{ .Release.Namespace }}"
  labels:
    app: "python-app-service-role-{{ .Release.Namespace }}"
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "python-app-service-role-binding-{{ .Release.Namespace }}"
  labels:
    app: "python-app-service-role-binding-{{ .Release.Namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "python-app-service-role-{{ .Release.Namespace }}"
subjects:
  - name: "python-app-service-account-{{ .Release.Namespace }}"
    kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
